name: coverage
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: go build -v ./...
    - run: go test -v -coverprofile cover.out ./...
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: f523ed60-1f84-421e-8040-d553c9190415
        file: ./cover.out
        flags: unittests
